.PHONY: all
all:
	pandoc report.md --standalone --pdf-engine=pdflatex -V documentclass=article -V papersize=a4 -V fontsize=11pt -V geometry:margin=23mm -V fontfamily=mathpazo -V colorlinks=true -V linkcolor=black -V urlcolor=black -o telemetry-yield-a40-research.pdf
