use super::*;
use crate::{generic::ProtocolDecoder, space_link};

// Generated by gr-satellites 5.5.0-2build2 encode_rs(dual_basis=True, interleave=1),
// GNU Radio 3.10.9.2. Neither FrameLift's encoder nor decoder generated these.
// Library SHA256 cd29749f3d9ad598c03b5d8a87f0c348afc51b3dc0d074b90209eae1a1d23162.
const TM_FRAME: &str = "00140709180025384b5e718497aabdd0e3f6091c2f4255687b8ea1b4c7da43a6";
const RS_WORD: &str = concat!(
    "00140709180025384b5e718497aabdd0e3f6091c2f4255687b8ea1b4c7da43a6",
    "dd2acae3a761fdaa591a0768556bc289e1a1a422f26c2aaa8c5d63f25343bf7b"
);
// External encoder was also run with the last FECF bit wrong. Parity is valid.
const RS_BAD_FECF: &str = concat!(
    "00140709180025384b5e718497aabdd0e3f6091c2f4255687b8ea1b4c7da43a7",
    "bb22ed112420e62171fc18c572320af029f8838fed8a0221971ce000744bd97a"
);

fn bits(bytes: &[u8]) -> Vec<u8> {
    bytes
        .iter()
        .flat_map(|byte| (0..8).rev().map(move |bit| (byte >> bit) & 1))
        .collect()
}

fn evidence(bits: &[u8]) -> Vec<f64> {
    bits.iter()
        .map(|&bit| 6.0 * (2.0 * bit as f64 - 1.0))
        .collect()
}

fn profile(code: fec::FrameCode) -> coded::CodedSyncConfig {
    coded::CodedSyncConfig {
        syncword: bits(&[0x1a, 0xcf, 0xfc, 0x1d]),
        maximum_sync_hamming: 1,
        frame_bytes: 32,
        code,
        randomizer: coded::Randomizer::None,
        validator: coded::FrameValidator::CcsdsTm {
            config: protocol::TmTransferFrameConfig {
                frame_length_bytes: 32,
                fecf_present: true,
            },
        },
        maximum_candidates: 32,
    }
}

fn rs_profile() -> coded::CodedSyncConfig {
    profile(fec::FrameCode::ReedSolomon {
        config: fec::ReedSolomonConfig::ccsds_rs255_223(1, 223 - 32),
    })
}

fn ldpc_profile() -> coded::CodedSyncConfig {
    profile(fec::FrameCode::Ldpc {
        config: fec::LdpcConfig::ccsds_tc512(),
    })
}

/// Separate generator-matrix encoder, using CCSDS 231.0-B-4 Table 4-2.
/// The production decoder constructs H instead; no production encoder is called.
fn tc512_encode(frame: &[u8]) -> Vec<u8> {
    const ROWS: [[u64; 4]; 4] = [
        [
            0x1d21794a22761fae,
            0x59945014257e130d,
            0x74d6054003794014,
            0x2dadeb9ca25ef12e,
        ],
        [
            0x60e0b6623c5ce512,
            0x4d2c81ecc7f469ab,
            0x20678dbfb7523ece,
            0x2b54b906a9dbe98c,
        ],
        [
            0xf6739bcf54273e77,
            0x167bda120c6c4774,
            0x4c071eff5e32a759,
            0x3138670c095c39b5,
        ],
        [
            0x28706bd045300258,
            0x2dab85f05b9201d0,
            0x8dfdee2d9d84ca88,
            0xb371fae63a4eb07e,
        ],
    ];
    assert_eq!(frame.len(), 32);
    let mut parity = [0u64; 4];
    for bit in 0..256 {
        if frame[bit / 8] & (1 << (7 - bit % 8)) != 0 {
            for block in 0..4 {
                parity[block] ^= ROWS[bit / 64][block].rotate_right((bit % 64) as u32);
            }
        }
    }
    bits(
        &[
            frame,
            &parity
                .into_iter()
                .flat_map(u64::to_be_bytes)
                .collect::<Vec<_>>(),
        ]
        .concat(),
    )
}

fn stream(profile: &coded::CodedSyncConfig, word: &[u8], damaged_marker: bool) -> Vec<f64> {
    let mut result = evidence(&profile.syncword);
    if damaged_marker {
        for bit in [2, 8, 15, 27] {
            result[bit] *= -1.0;
        }
    }
    let mut coded = evidence(word);
    coded::derandomize(&mut coded, &profile.randomizer);
    result.extend(coded);
    result
}

#[test]
fn damaged_asm_recovers_external_gr_satellites_rs_codeword_with_fecf() {
    let expected = hex::decode(TM_FRAME).unwrap();
    let word = bits(&hex::decode(RS_WORD).unwrap());
    for randomizer in [
        coded::Randomizer::None,
        coded::Randomizer::CcsdsTm255,
        coded::Randomizer::CcsdsTm131071,
    ] {
        let mut config = rs_profile();
        config.randomizer = randomizer;
        let mut input = vec![-3.0; 17];
        input.extend(stream(&config, &word, true));
        // Two erroneous received RS symbols, in addition to four marker errors.
        for position in [17 + 32 + 71, 17 + 32 + 173] {
            input[position] *= -0.1;
        }
        assert!(coded::decode_sync(&input, 0.0, &config).unwrap().is_empty());
        let result = decode(&input, 0.0, &config, &Config::default()).unwrap();
        assert_eq!(result.baseline_frames, 0);
        assert_eq!(result.extra_frames, 1);
        assert_eq!(result.frames[0].frame, expected);
        assert!(
            result.frames[0]
                .validation_layers
                .iter()
                .any(|l| l == "ccsds_tm_fecf_crc16")
        );
        let candidate = result
            .candidates
            .iter()
            .find(|c| c.marker_start_bit == 17)
            .unwrap();
        assert_eq!(candidate.outcome, Outcome::Accepted);
        assert_eq!(candidate.marker_hamming, 4);
        assert_eq!(candidate.corrected_symbols, Some(2));
        assert!(candidate.codeword_distance.unwrap() < 0.001);
    }
}

#[test]
fn damaged_marker_tc512_independent_generator_and_soft_error_recover() {
    // A synthetic TM payload in a TC512 coding envelope, NOT a standard TC CLTU.
    let config = ldpc_profile();
    let frame = hex::decode(TM_FRAME).unwrap();
    let mut input = stream(&config, &tc512_encode(&frame), true);
    input[32 + 143] *= -0.1;
    assert!(coded::decode_sync(&input, 0.0, &config).unwrap().is_empty());
    let result = decode(&input, 0.0, &config, &Config::default()).unwrap();
    assert_eq!(result.frames.len(), 1);
    assert_eq!(result.frames[0].frame, frame);
    assert_eq!(result.candidates[0].rank, Some(0));
    assert!(result.candidates[0].iterations.unwrap() > 0);
}

#[test]
fn clean_hard_asm_baseline_order_layers_and_bytes_remain_exact() {
    for (config, word) in [
        (rs_profile(), bits(&hex::decode(RS_WORD).unwrap())),
        (
            ldpc_profile(),
            tc512_encode(&hex::decode(TM_FRAME).unwrap()),
        ),
    ] {
        let input = stream(&config, &word, false);
        let baseline = coded::decode_sync(&input, 0.0, &config).unwrap();
        let result = decode(&input, 0.0, &config, &Config::default()).unwrap();
        assert_eq!(baseline.len(), 1);
        assert_eq!(result.frames, baseline);
        assert_eq!(result.fec_trials, 0);
        assert_eq!(result.extra_frames, 0);
        // The legacy config serialization has no new field or default behaviour.
        assert!(
            serde_json::to_value(config)
                .unwrap()
                .get("recovery")
                .is_none()
        );
    }
}

#[test]
fn crc_does_not_rank_candidates_and_parity_alone_is_not_integrity() {
    let config = rs_profile();
    let mut input = stream(&config, &bits(&hex::decode(RS_BAD_FECF).unwrap()), true);
    input.extend(vec![-2.0; 39]);
    let valid_start = input.len();
    let mut valid = stream(&config, &bits(&hex::decode(RS_WORD).unwrap()), true);
    valid[32 + 81] *= -0.1;
    input.extend(valid);
    let result = decode(&input, 0.0, &config, &Config::default()).unwrap();
    let bad = result
        .candidates
        .iter()
        .find(|c| c.marker_start_bit == 0)
        .unwrap();
    let good = result
        .candidates
        .iter()
        .find(|c| c.marker_start_bit == valid_start)
        .unwrap();
    assert_eq!(bad.rank, Some(0));
    assert_eq!(bad.codeword_distance, Some(0.0));
    assert!(bad.fec_converged);
    assert_eq!(bad.outcome, Outcome::IntegrityRejected);
    assert!(good.rank.unwrap() > bad.rank.unwrap());
    assert_eq!(good.outcome, Outcome::Accepted);
    assert_eq!(result.frames.len(), 1);
    assert_eq!(hex::encode(&result.frames[0].frame), TM_FRAME);
}

#[test]
fn valid_ldpc_syndrome_with_bad_fecf_or_invalid_tm_header_is_rejected() {
    let config = ldpc_profile();
    let clean = hex::decode(TM_FRAME).unwrap();
    for defect in 0..2 {
        let mut bytes = clean.clone();
        if defect == 0 {
            bytes[31] ^= 1;
        } else {
            bytes[0] |= 0x40; // Unsupported TM transfer-frame version.
            let crc = protocol::compute_tm_fecf(&bytes[..30]);
            bytes[30..].copy_from_slice(&crc.to_be_bytes());
        }
        let input = stream(&config, &tc512_encode(&bytes), true);
        let result = decode(&input, 0.0, &config, &Config::default()).unwrap();
        assert!(result.frames.is_empty());
        assert!(result.candidates[0].fec_converged);
        assert_eq!(result.candidates[0].outcome, Outcome::IntegrityRejected);
    }
}

#[test]
fn wrong_phase_wrong_randomizer_and_wrong_code_profile_never_create_a_frame() {
    let config = ldpc_profile();
    let word = tc512_encode(&hex::decode(TM_FRAME).unwrap());
    let clean = stream(&config, &word, true);
    let inverted: Vec<_> = clean.iter().map(|v| -v).collect();
    assert!(
        decode(&inverted, 0.0, &config, &Config::default())
            .unwrap()
            .frames
            .is_empty()
    );
    let mut shifted = clean.clone();
    shifted[32..].rotate_left(1);
    assert!(
        decode(&shifted, 0.0, &config, &Config::default())
            .unwrap()
            .frames
            .is_empty()
    );
    let mut wrong = config.clone();
    wrong.randomizer = coded::Randomizer::CcsdsTc255;
    assert!(
        decode(&clean, 0.0, &wrong, &Config::default())
            .unwrap()
            .frames
            .is_empty()
    );
    let mut wrong = config;
    if let fec::FrameCode::Ldpc { config } = &mut wrong.code {
        config.output_bits.reverse();
    }
    let result = decode(&clean, 0.0, &wrong, &Config::default()).unwrap();
    assert!(result.frames.is_empty());
    assert!(result.candidates[0].fec_converged);
    assert_eq!(result.candidates[0].outcome, Outcome::IntegrityRejected);
}

#[test]
fn noise_erased_codeword_and_implausible_distance_are_rejected() {
    let config = ldpc_profile();
    let word = tc512_encode(&hex::decode(TM_FRAME).unwrap());
    let mut input = stream(&config, &word, true);
    input[32..].fill(0.0);
    assert!(
        decode(&input, 0.0, &config, &Config::default())
            .unwrap()
            .frames
            .is_empty()
    );
    let mut rng = 0x51ead01_u64;
    for _ in 0..64 {
        let input: Vec<_> = (0..1024)
            .map(|_| {
                rng ^= rng << 13;
                rng ^= rng >> 7;
                rng ^= rng << 17;
                if rng & 1 == 0 { -1.0 } else { 1.0 }
            })
            .collect();
        assert!(
            decode(&input, 0.0, &config, &Config::default())
                .unwrap()
                .frames
                .is_empty()
        );
    }
    let mut input = stream(&config, &word, true);
    input[32 + 45] *= -0.1;
    let recovery = Config {
        maximum_codeword_distance: 0.0,
        ..Config::default()
    };
    let result = decode(&input, 0.0, &config, &recovery).unwrap();
    assert!(result.frames.is_empty());
    assert_eq!(result.candidates[0].outcome, Outcome::DistanceRejected);
}

#[test]
fn input_and_all_resource_budgets_fail_closed_without_partial_union() {
    let config = rs_profile();
    let word = bits(&hex::decode(RS_WORD).unwrap());
    let mut input = stream(&config, &word, false);
    input.extend(stream(&config, &word, true));
    input.extend(stream(&config, &word, true));
    assert_eq!(coded::decode_sync(&input, 0.0, &config).unwrap().len(), 1);
    for recovery in [
        Config {
            maximum_offsets: 1,
            ..Config::default()
        },
        Config {
            maximum_fec_trials: 1,
            ..Config::default()
        },
        Config {
            work_budget: 1,
            ..Config::default()
        },
        Config {
            work_budget: 40_000,
            ..Config::default()
        },
    ] {
        let error = decode(&input, 0.0, &config, &recovery).unwrap_err();
        assert!(error.contains("budget exceeded"), "{error}");
    }
    for invalid in [f64::NAN, f64::INFINITY, 1e101] {
        let mut invalid_input = input.clone();
        invalid_input[5] = invalid;
        assert!(decode(&invalid_input, 0.0, &config, &Config::default()).is_err());
        assert!(decode(&input, invalid, &config, &Config::default()).is_err());
    }
    let short = stream(&config, &word, true);
    assert!(
        decode(&short[..short.len() - 1], 0.0, &config, &Config::default())
            .unwrap()
            .frames
            .is_empty()
    );
}

#[test]
fn unsupported_profiles_and_malformed_configuration_are_explicit_errors() {
    let mut config = rs_profile();
    config.code = fec::FrameCode::None;
    assert!(
        Config::default()
            .validate(&config)
            .unwrap_err()
            .contains("unsupported")
    );
    let config = rs_profile();
    for recovery in [
        Config {
            maximum_marker_hamming: 1,
            ..Config::default()
        },
        Config {
            minimum_marker_correlation: f64::NAN,
            ..Config::default()
        },
        Config {
            maximum_codeword_distance: -0.1,
            ..Config::default()
        },
        Config {
            maximum_fec_trials: 0,
            ..Config::default()
        },
    ] {
        assert!(recovery.validate(&config).is_err());
    }
    let mut no_integrity = config.clone();
    no_integrity.validator = coded::FrameValidator::CcsdsTm {
        config: protocol::TmTransferFrameConfig {
            frame_length_bytes: 32,
            fecf_present: false,
        },
    };
    assert!(Config::default().validate(&no_integrity).is_err());
    assert!(
        serde_json::from_value::<fec::FrameCode>(serde_json::json!({"kind":"convolutional_k7"}))
            .is_err()
    );
    assert!(serde_json::from_value::<Config>(serde_json::json!({"unknown_option": true})).is_err());
}

#[test]
fn generic_receiver_protocol_dispatches_optional_path_and_fingerprints_it() {
    let config = rs_profile();
    let input = stream(&config, &bits(&hex::decode(RS_WORD).unwrap()), true);
    let json = serde_json::json!({"type":"fec_assisted_sync", "config":config, "recovery":{}});
    let protocol: crate::generic::ProtocolConfig = serde_json::from_value(json).unwrap();
    protocol.validate().unwrap();
    let decoded = protocol.decode(&input, 0.0).unwrap();
    assert_eq!(decoded.len(), 1);
    assert_eq!(hex::encode(&decoded[0].frame), TM_FRAME);
    let baseline = crate::generic::ProtocolConfig::CodedSync { config };
    assert!(baseline.decode(&input, 0.0).unwrap().is_empty());
    assert_ne!(protocol.resume_identity(), baseline.resume_identity());
    let changed = crate::generic::ProtocolConfig::FecAssistedSync {
        config: rs_profile(),
        recovery: Config {
            maximum_marker_hamming: 5,
            ..Config::default()
        },
    };
    assert_ne!(protocol.resume_identity(), changed.resume_identity());
}

#[test]
fn tc128_primitive_has_the_same_integrity_boundary() {
    let mut config = profile(fec::FrameCode::Ldpc {
        config: fec::LdpcConfig::ccsds_tc128(),
    });
    config.frame_bytes = 8;
    config.validator = coded::FrameValidator::SpaceLink {
        config: space_link::SpaceLinkConfig::CspV1 {
            crc32: space_link::CspCrc32Mode::RequiredHeaderAndPayload,
        },
    };
    let mut frame = vec![0x44, 0x30, 0x41, 0x01];
    frame.extend(space_link::csp_crc32c(&frame).to_be_bytes());
    // CCSDS 231.0-B-4 Table 4-1, independent generator circulants.
    let rows = [
        0x0e69166bef4c0bc2u64,
        0x7766137ebb248418,
        0xc480feb9cd53a713,
        0x4eaa22fa465eea11,
    ];
    let mut parity = 0_u64;
    for bit in 0..64 {
        if frame[bit / 8] & (1 << (7 - bit % 8)) != 0 {
            for block in 0..4 {
                let chunk = (rows[bit / 16] >> (48 - block * 16)) as u16;
                parity ^= u64::from(chunk.rotate_right((bit % 16) as u32)) << (48 - block * 16);
            }
        }
    }
    let word = bits(&[frame.as_slice(), &parity.to_be_bytes()].concat());
    let input = stream(&config, &word, true);
    let result = decode(&input, 0.0, &config, &Config::default()).unwrap();
    assert_eq!(result.frames[0].frame, frame);
}

#[test]
fn real_iq_file_path_recovers_damaged_asm_and_revalidates_checkpoint_integrity() {
    use crate::generic;
    use serde_json::json;
    use sha2::{Digest, Sha256};
    let directory = tempfile::tempdir().unwrap();
    let input = directory.path().join("damaged-marker.cf32");
    let config = rs_profile();
    let symbols = stream(&config, &bits(&hex::decode(RS_WORD).unwrap()), true);
    let mut iq = Vec::new();
    // Independent rectangular BPSK waveform generation; no receiver internals.
    for _ in 0..4 {
        for symbol in &symbols {
            for _ in 0..8 {
                let sign = if *symbol > 0.0 { 0.8_f32 } else { -0.8 };
                iq.extend_from_slice(&sign.to_le_bytes());
                iq.extend_from_slice(&0.0_f32.to_le_bytes());
            }
        }
    }
    std::fs::write(&input, &iq).unwrap();
    let plan: generic::Plan = serde_json::from_value(json!({
        "format":"cf32_le", "sample_rate_hz":48000,
        "window_seconds":1.0, "hop_seconds":1.0,
        "protocols":{"tm":{"type":"fec_assisted_sync", "config":config, "recovery":{}}},
        "hypotheses":[{"protocol_id":"tm", "waveform":{
            "hypothesis_id":"bpsk", "demodulator_id":"iq_bpsk", "decimation":1,
            "dsp":{"baud":6000.0,"mode":"bpsk","rate_errors_ppm":[0.0],
                "phase_bins":4,"top_timing":4,"bank":"full"}
        }}]
    }))
    .unwrap();
    let receiver = generic::GenericReceiver::with_builtin_demodulators();
    let output = directory.path().join("recovery");
    let result = receiver.decode_file(&input, &output, &plan, 1).unwrap();
    assert_eq!(result["status"], "complete");
    assert_eq!(result["unique_frame_count"], 1, "{result}");
    assert_eq!(result["frames"][0]["frame_hex"], TM_FRAME);
    let resumed = receiver
        .decode_file_resumable(&input, &output, &plan, 1, true)
        .unwrap();
    assert_eq!(resumed, result);
    let mut baseline_plan = plan.clone();
    baseline_plan
        .protocols
        .insert("tm".into(), generic::ProtocolConfig::CodedSync { config });
    let baseline = receiver
        .decode_file(
            &input,
            &directory.path().join("baseline"),
            &baseline_plan,
            1,
        )
        .unwrap();
    assert_eq!(baseline["unique_frame_count"], 0, "{baseline}");
    let checkpoint = output.join("windows/00000000.json");
    let original: serde_json::Value =
        serde_json::from_slice(&std::fs::read(&checkpoint).unwrap()).unwrap();
    for removed in ["ccsds_tm_fecf_crc16", "reed_solomon_syndrome_verified"] {
        let mut modified = original.clone();
        modified["window"]["frames"][0]["validation_layers"]
            .as_array_mut()
            .unwrap()
            .retain(|layer| layer != removed);
        modified.as_object_mut().unwrap().remove("content_sha256");
        modified["content_sha256"] = json!(hex::encode(Sha256::digest(
            crate::ledger::canonical_json(&modified).unwrap().as_bytes()
        )));
        std::fs::write(&checkpoint, serde_json::to_vec(&modified).unwrap()).unwrap();
        let error = receiver
            .decode_file_resumable(&input, &output, &plan, 1, true)
            .unwrap_err();
        assert!(error.contains("lost required"), "{error}");
    }
}
