"""Serialized reconstruction of the SatNOGS flowgraphs-1.5 FSK front end.

The historical graph contains a split AFC path.  Running that split through a
modern GNU Radio thread-per-block scheduler introduces small floating-point
differences between runs.  This module executes the same enabled blocks in a
fixed topological order and materializes each intermediate vector.  The moving
average's source-level ``max_iter=4096`` recurrence is executed with fixed
4096-sample work partitions; the remaining individual GNU Radio blocks are
retained.  Scheduler partitioning is therefore removed as an experimental axis.

This is a GNU Radio 3.10 runtime substitute for the unpinned historical 3.8
runtime, not a claim of bit-exact historical execution.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
from pathlib import Path
from typing import Sequence


FLOWGRAPHS_TAG = "1.5"
FLOWGRAPHS_FSK_SHA256 = (
    "dda3c64161bdffacbf516a86e81e87fce6294815ec22c24770e747d0b9f38032"
)
FLOWGRAPHS_TAG_COMMIT = "c135a61558a61f3249737282c00095832bc1ba10"
FLOWGRAPHS_OBSERVATION_PROVENANCE_COMMIT = (
    "ac654732b48434a248e8a26f165315fa250d658d"
)
GR_SATNOGS_COMMIT = "8d94dc292ace327dcd15dba66dd2020031b2d5c7"


@dataclass(frozen=True)
class Tag15FrontendSpec:
    """Frozen enabled-block parameters from ``generic/fsk.grc`` tag 1.5."""

    iq_rate_hz: int = 57_600
    baudrate: int = 9_600
    graph_decimation: int = 6
    channel_decimation: int = 3
    relaxed_cutoff_hz: float = 12_000.0
    relaxed_transition_hz: float = 4_800.0
    afc_discriminator_gain: float = 1.0
    afc_average_length: int = 1_024
    afc_vco_sensitivity: float = -57_600.0
    signal_delay_samples: int = 512
    channel_cutoff_hz: float = 6_000.0
    channel_transition_hz: float = 1_200.0
    discriminator_gain: float = 1.2
    dc_blocker_length: int = 1_024
    clock_omega: float = 2.0
    clock_gain_omega: float = 2.0 * 3.141592653589793 / 100.0
    clock_mu: float = 0.5
    clock_gain_mu: float = 0.5 / 8.0
    clock_omega_relative_limit: float = 0.01
    iq_normalization_scale: float = 16_768.0


@dataclass(frozen=True)
class Tag15FrontendMetrics:
    """Hashes and sizes for every materialized front-end stage."""

    input_complex_samples: int
    output_float_samples: int
    stage_sample_counts: tuple[tuple[str, int], ...]
    stage_sha256: tuple[tuple[str, str], ...]


def _sha256_array(values) -> str:
    return hashlib.sha256(values.tobytes(order="C")).hexdigest()


def _require_gnuradio():
    try:
        from gnuradio import analog, blocks, digital, filter as gr_filter, gr
        from gnuradio.fft import window
        from gnuradio.filter import firdes
    except ImportError as error:  # pragma: no cover - depends on host runtime
        raise RuntimeError("GNU Radio is required for the tag-1.5 reconstruction") from error
    return analog, blocks, digital, gr_filter, gr, window, firdes


def tag15_filter_taps(
    spec: Tag15FrontendSpec = Tag15FrontendSpec(),
):
    """Return the exact taps generated by the installed GNU Radio firdes.

    The tag-1.5 graph specifies cutoff, transition width, Hamming window, and
    beta rather than literal taps.  The generated vectors are kept as float32,
    matching ``fir_filter_ccf``.
    """

    import numpy as np

    _, _, _, _, _, window, firdes = _require_gnuradio()
    relaxed = np.asarray(
        firdes.low_pass(
            1.0,
            spec.iq_rate_hz,
            spec.relaxed_cutoff_hz,
            spec.relaxed_transition_hz,
            window.WIN_HAMMING,
            6.76,
        ),
        dtype=np.float32,
    )
    channel = np.asarray(
        firdes.low_pass(
            1.0,
            spec.iq_rate_hz,
            spec.channel_cutoff_hz,
            spec.channel_transition_hz,
            window.WIN_HAMMING,
            6.76,
        ),
        dtype=np.float32,
    )
    return relaxed, channel


def read_tag15_c16le_window(
    path: str | Path,
    *,
    start_seconds: float,
    duration_seconds: float,
    spec: Tag15FrontendSpec = Tag15FrontendSpec(),
):
    """Read a bounded little-endian interleaved-IQ window as complex64."""

    import numpy as np

    if start_seconds < 0 or duration_seconds <= 0:
        raise ValueError("invalid IQ window")
    if spec.iq_rate_hz <= 0 or spec.iq_normalization_scale <= 0:
        raise ValueError("invalid sample format")
    source = Path(path)
    start_sample = int(round(start_seconds * spec.iq_rate_hz))
    sample_count = int(round(duration_seconds * spec.iq_rate_hz))
    raw = np.fromfile(
        source,
        dtype="<i2",
        count=sample_count * 2,
        offset=start_sample * 4,
    )
    if raw.size != sample_count * 2:
        raise ValueError("window extends beyond IQ file")
    pairs = raw.reshape(-1, 2)
    real = pairs[:, 0].astype(np.float32)
    imag = pairs[:, 1].astype(np.float32)
    return np.asarray(
        (real + 1j * imag) / np.float32(spec.iq_normalization_scale),
        dtype=np.complex64,
    )


def _run_complex_to_complex(values, make_block, *, max_noutput_items: int):
    import numpy as np

    _, blocks, _, _, gr, _, _ = _require_gnuradio()
    top = gr.top_block("tag15_serialized_cc")
    source = blocks.vector_source_c(values.tolist(), False)
    block = make_block()
    sink = blocks.vector_sink_c()
    top.connect(source, block, sink)
    top.run(max_noutput_items=max_noutput_items)
    return np.asarray(sink.data(), dtype=np.complex64)


def _run_complex_to_float(values, make_block, *, max_noutput_items: int):
    import numpy as np

    _, blocks, _, _, gr, _, _ = _require_gnuradio()
    top = gr.top_block("tag15_serialized_cf")
    source = blocks.vector_source_c(values.tolist(), False)
    block = make_block()
    sink = blocks.vector_sink_f()
    top.connect(source, block, sink)
    top.run(max_noutput_items=max_noutput_items)
    return np.asarray(sink.data(), dtype=np.float32)


def _run_float_to_float(values, make_block, *, max_noutput_items: int):
    import numpy as np

    _, blocks, _, _, gr, _, _ = _require_gnuradio()
    top = gr.top_block("tag15_serialized_ff")
    source = blocks.vector_source_f(values.tolist(), False)
    block = make_block()
    sink = blocks.vector_sink_f()
    top.connect(source, block, sink)
    top.run(max_noutput_items=max_noutput_items)
    return np.asarray(sink.data(), dtype=np.float32)


def deterministic_moving_average_ff(
    values: Sequence[float],
    *,
    length: int,
    scale: float,
    max_iter: int,
):
    """Execute GNU Radio's scalar moving-average recurrence deterministically.

    GNU Radio recomputes the float accumulator at every scheduler ``work``
    call, and caps each call at ``max_iter``.  Different scheduler partitions
    therefore change low-order float bits.  This implementation freezes calls
    to consecutive chunks of exactly ``max_iter`` items and mirrors the 3.8 and
    3.10 source recurrence using float32 operations.
    """

    import numpy as np

    source = np.asarray(values, dtype=np.float32)
    if source.ndim != 1 or length < 1 or max_iter < 1:
        raise ValueError("invalid moving-average input or parameters")
    padded = np.concatenate(
        (np.zeros(length - 1, dtype=np.float32), source)
    )
    output = np.empty(source.size, dtype=np.float32)
    scale32 = np.float32(scale)
    for start in range(0, source.size, max_iter):
        stop = min(start + max_iter, source.size)
        accumulator = np.float32(0.0)
        for index in range(start, start + length - 1):
            accumulator = np.float32(accumulator + padded[index])
        for output_index in range(start, stop):
            entering = padded[output_index + length - 1]
            accumulator = np.float32(accumulator + entering)
            output[output_index] = np.float32(accumulator * scale32)
            accumulator = np.float32(accumulator - padded[output_index])
    return output


def run_tag15_preclock(
    iq: Sequence[complex],
    *,
    spec: Tag15FrontendSpec = Tag15FrontendSpec(),
    max_noutput_items: int = 8_192,
):
    """Run the enabled tag-1.5 FSK blocks through the long DC blocker.

    Each block is run in isolation and the AFC split is joined by array index.
    This preserves block-level behavior while making execution order explicit.
    """

    import numpy as np

    analog, blocks, _, gr_filter, gr, _, _ = _require_gnuradio()
    values = np.asarray(iq, dtype=np.complex64)
    if values.ndim != 1 or values.size < 4_096:
        raise ValueError("IQ must be a one-dimensional window of at least 4096 samples")
    if values.size % spec.channel_decimation:
        raise ValueError("IQ length must be divisible by channel decimation")
    if not np.all(np.isfinite(values)):
        raise ValueError("IQ must be finite")
    if max_noutput_items < 1:
        raise ValueError("max_noutput_items must be positive")
    if spec.iq_rate_hz != spec.baudrate * spec.graph_decimation:
        raise ValueError("tag-1.5 rate contract is not satisfied")
    if spec.channel_decimation != spec.graph_decimation // 2:
        raise ValueError("tag-1.5 channel decimation contract is not satisfied")

    relaxed_taps, channel_taps = tag15_filter_taps(spec)
    stages: list[tuple[str, object]] = [("input", values)]
    relaxed = _run_complex_to_complex(
        values,
        lambda: gr_filter.fir_filter_ccf(1, relaxed_taps),
        max_noutput_items=max_noutput_items,
    )
    stages.append(("relaxed_lpf", relaxed))
    afc_discriminator = _run_complex_to_float(
        relaxed,
        lambda: analog.quadrature_demod_cf(spec.afc_discriminator_gain),
        max_noutput_items=max_noutput_items,
    )
    stages.append(("afc_discriminator", afc_discriminator))
    afc_average = deterministic_moving_average_ff(
        afc_discriminator,
        length=spec.afc_average_length,
        scale=1.0 / spec.afc_average_length,
        max_iter=4_096,
    )
    stages.append(("afc_moving_average", afc_average))
    afc_vco = _run_float_to_complex_vco(
        afc_average,
        sample_rate_hz=spec.iq_rate_hz,
        sensitivity=spec.afc_vco_sensitivity,
        max_noutput_items=max_noutput_items,
    )
    stages.append(("afc_vco", afc_vco))

    delayed = np.zeros(values.size, dtype=np.complex64)
    delayed[spec.signal_delay_samples :] = values[: -spec.signal_delay_samples]
    stages.append(("signal_delay", delayed))
    corrected = np.asarray(delayed * afc_vco, dtype=np.complex64)
    stages.append(("afc_corrected", corrected))
    channel = _run_complex_to_complex(
        corrected,
        lambda: gr_filter.fir_filter_ccf(
            spec.channel_decimation,
            channel_taps,
        ),
        max_noutput_items=max_noutput_items,
    )
    stages.append(("channel_lpf_decimated", channel))
    discriminator = _run_complex_to_float(
        channel,
        lambda: analog.quadrature_demod_cf(spec.discriminator_gain),
        max_noutput_items=max_noutput_items,
    )
    stages.append(("fsk_discriminator", discriminator))
    preclock = _run_float_to_float(
        discriminator,
        lambda: gr_filter.dc_blocker_ff(spec.dc_blocker_length, True),
        max_noutput_items=max_noutput_items,
    )
    stages.append(("dc_blocker_long", preclock))

    metrics = Tag15FrontendMetrics(
        input_complex_samples=int(values.size),
        output_float_samples=int(preclock.size),
        stage_sample_counts=tuple(
            (name, int(stage.size)) for name, stage in stages
        ),
        stage_sha256=tuple(
            (name, _sha256_array(stage)) for name, stage in stages
        ),
    )
    return preclock, metrics


def _run_float_to_complex_vco(
    values,
    *,
    sample_rate_hz: float,
    sensitivity: float,
    max_noutput_items: int,
):
    _, blocks, _, _, gr, _, _ = _require_gnuradio()
    return _run_float_to_complex(
        values,
        lambda: blocks.vco_c(sample_rate_hz, sensitivity, 1.0),
        max_noutput_items=max_noutput_items,
    )


def _run_float_to_complex(values, make_block, *, max_noutput_items: int):
    import numpy as np

    _, blocks, _, _, gr, _, _ = _require_gnuradio()
    top = gr.top_block("tag15_serialized_fc")
    source = blocks.vector_source_f(values.tolist(), False)
    block = make_block()
    sink = blocks.vector_sink_c()
    top.connect(source, block, sink)
    top.run(max_noutput_items=max_noutput_items)
    return np.asarray(sink.data(), dtype=np.complex64)


def run_tag15_clock(
    preclock: Sequence[float],
    *,
    spec: Tag15FrontendSpec = Tag15FrontendSpec(),
    max_noutput_items: int = 8_192,
) -> bytes:
    """Run the tag-1.5 M&M clock and binary slicer on one isolated vector."""

    import numpy as np

    _, blocks, digital, _, gr, _, _ = _require_gnuradio()
    values = np.asarray(preclock, dtype=np.float32)
    if values.ndim != 1 or values.size < 256 or not np.all(np.isfinite(values)):
        raise ValueError("preclock must be a finite one-dimensional vector")
    top = gr.top_block("tag15_serialized_clock")
    source = blocks.vector_source_f(values.tolist(), False)
    clock = digital.clock_recovery_mm_ff(
        spec.clock_omega,
        spec.clock_gain_omega,
        spec.clock_mu,
        spec.clock_gain_mu,
        spec.clock_omega_relative_limit,
    )
    slicer = digital.binary_slicer_fb()
    sink = blocks.vector_sink_b()
    top.connect(source, clock, slicer, sink)
    top.run(max_noutput_items=max_noutput_items)
    return bytes(sink.data())
