//! Bounded metadata-only follow-up of an existing exposure inventory. Never releases a cohort.
use serde_json::{json,Value};use sha2::{Digest,Sha256};
use std::{collections::{BTreeMap,BTreeSet},fs,path::{Path,PathBuf},io::Write};
type R<T>=Result<T,Box<dyn std::error::Error>>;
const ROOT:&str="/home/ubuntu/telemetry-yield";const MAX:u64=64*1024*1024;
fn load(p:&Path)->R<(Value,Value)>{let m=fs::metadata(p)?;if m.len()>MAX{return Err("metadata exceeds64MiB".into());}let b=fs::read(p)?;let v=serde_json::from_slice(&b)?;Ok((v,json!({"path":p,"bytes":b.len(),"sha256":hex::encode(Sha256::digest(&b))})))}
fn path(s:&str)->PathBuf{let p=Path::new(s);if p.is_absolute(){p.to_owned()}else{Path::new(ROOT).join(p)}}
fn strings(v:&Value,key:&str,out:&mut BTreeSet<String>){match v {Value::String(s) if ["path","input","source","wav","audio","source_path","input_path","capture"].contains(&key)=>{if s.contains('/')&&!s.starts_with("https:"){out.insert(path(s).to_string_lossy().into_owned());}},Value::Object(m)=>{for(k,v)in m{strings(v,k,out);}},Value::Array(a) if a.len()<100=>{for v in a{strings(v,key,out);}},_=>{}}}
fn sources(v:&Value)->BTreeSet<String>{let mut out=BTreeSet::new();for key in["source","input","audio","recording","capture","source_path","input_path","wav","codec_input_binding"]{strings(&v[key],key,&mut out);}out}
fn identity_mentions(v:&Value,p:&str)->bool{match v{Value::Object(m)=>{if m.get("path").and_then(Value::as_str)==Some(p)&&m.get("sha256").and_then(Value::as_str).is_some_and(|s|s.len()==64){return true;}m.values().any(|v|identity_mentions(v,p))},Value::Array(a)=>a.iter().any(|v|identity_mentions(v,p)),_=>false}}
fn nonwaveform_contract(v:&Value)->Option<&'static str>{
 if v["schema_version"]=="paired-cluster-bootstrap-v1"&&v["aligned_prediction_count"].is_number()&&v["relative_brier_reduction"].is_number(){return Some("paired predictive-model Brier bootstrap statistics; not a receiver attempt");}
 if v["task"]=="decode_success_given_signal"&&v.get("fit").is_some()&&v.get("panel_sha256").is_some()&&v.get("lead_hours").is_some(){return Some("weather-model parameter fit bound to panel hash; not a receiver attempt");}
 if v["schema"].as_str().is_some_and(|s|s.starts_with("innovation-receiver-freeze")||s=="innovation-v2-receiver-freeze-v1"){return Some("receiver build freeze record, not a waveform decode result");}
 if ["adaptive-pcm-synthetic-smoke-result-v1","adaptive-pcm-synthetic-smoke-result-v2","sequence-transfer-synthetic-symbol-probe-result-v1"].contains(&v["schema"].as_str().unwrap_or(""))&&v["synthetic_only"]==true{return Some("typed synthetic experiment summary explicitly declares synthetic_only");}
 if v["schema"]=="innovation-controls-result-v1"&&v["synthetic_development_only"]==true{return Some("typed declared synthetic development result summary");}None
}
fn identities<'a>(v:&'a Value,out:&mut Vec<&'a Value>){match v{Value::Object(m)=>{if m.get("path").and_then(Value::as_str).is_some()&&m.get("sha256").and_then(Value::as_str).is_some_and(|s|s.len()==64){out.push(v);}for x in m.values(){identities(x,out);}},Value::Array(a)=>for x in a{identities(x,out);},_=>{}}}
fn group(p:&str)->String{Path::new(p).strip_prefix(Path::new(ROOT).join("work")).ok().and_then(|x|x.components().next()).map_or_else(||"outside-work".into(),|x|x.as_os_str().to_string_lossy().into_owned())}
fn main()->R<()>{
 let root=Path::new(ROOT);let original=root.join("work/innovation-exposure-audit-20260911-v4/lineage-review-partial-v2.json");let (prior,prior_id)=load(&original)?;let (inventory,inventory_id)=load(&root.join("work/innovation-exposure-audit-20260911-v4/exposure-manifest.json"))?;
 let mut known=BTreeMap::<String,Value>::new();for a in inventory["identified_exposure_evidence"].as_array().ok_or("missing identified evidence")?{known.insert(a["path"].as_str().ok_or("missing evidence path")?.into(),a["keys"].clone());}
 let mut metadata=BTreeMap::<String,(Value,Value)>::new();let mut issues=Vec::new();let mut rows=Vec::new();
 for artifact in prior["unresolved_unlinked_artifacts"].as_array().ok_or("missing unresolved artifacts")?{
  let p=artifact["path"].as_str().ok_or("missing artifact path")?;let ap=Path::new(p);let mut evidence=Vec::new();let mut links=BTreeSet::new();let mut resolved=None::<String>;let mut schema=Value::Null;let mut topkeys=Vec::new();
  if ap.extension().is_some_and(|s|s=="json") {match load(ap){Ok((v,id))=>{schema=v["schema"].clone();topkeys=v.as_object().map_or(Vec::new(),|m|m.keys().cloned().collect());
   if let Some(reason)=nonwaveform_contract(&v){resolved=Some(reason.into());evidence.push(id.clone());}
   for src in sources(&v){if let Some(keys)=known.get(&src){links.extend(keys.as_array().unwrap().iter().filter_map(Value::as_str).map(str::to_owned));evidence.push(json!({"artifact":id,"explicit_source_path":src,"prior_exposure_keys":keys}));}}
   metadata.insert(p.into(),(v,id));},Err(e)=>issues.push(json!({"path":p,"error":e.to_string()}))}}
  // Only narrowly named sibling/parent manifests are candidates; their contents must bind the exact artifact.
  let mut dir=ap.parent();let mut candidates=Vec::new();for _ in 0..5 {if let Some(d)=dir{for name in["input.json","plan.json","manifest.json","generation.json","result.json","process-receipt.json"]{let q=d.join(name);if q!=ap&&q.is_file(){candidates.push(q);}}dir=d.parent();}}
  let mut named_manifests=Vec::new();
  for cp in candidates{let key=cp.to_string_lossy().into_owned();if !metadata.contains_key(&key){match load(&cp){Ok(pair)=>{metadata.insert(key.clone(),pair);},Err(e)=>{issues.push(json!({"path":cp,"error":e.to_string()}));continue;}}}let(v,id)=&metadata[&key];
   named_manifests.push(json!({"identity":id,"schema":v["schema"],"exact_artifact_identity_mentioned":identity_mentions(v,p)}));
   if identity_mentions(v,p){for src in sources(v){if let Some(keys)=known.get(&src){links.extend(keys.as_array().unwrap().iter().filter_map(Value::as_str).map(str::to_owned));evidence.push(json!({"artifact":id,"exact_child_identity_bound":p,"explicit_source_path":src,"prior_exposure_keys":keys}));}}}
  }
  // A seed-bearing input sidecar and a typed synthetic generation plan must be connected by exact source path.
  let sidecar=ap.parent().unwrap().join("input.json").to_string_lossy().into_owned();if let Some((side,sideid))=metadata.get(&sidecar){
   let input_matches=identity_mentions(side,p)||metadata.get(p).is_some_and(|(v,_)|sources(v).iter().any(|sp|identity_mentions(side,sp)));
   if side["seed_hex"].is_string()&&input_matches{for candidate in &named_manifests{let key=candidate["identity"]["path"].as_str().unwrap();let(v,id)=&metadata[key];if ["adaptive-pcm-synthetic-smoke-v1","adaptive-pcm-synthetic-smoke-v2","innovation-controls-plan-v1"].contains(&v["schema"].as_str().unwrap_or("")) {
     resolved=Some("declared synthetic input: exact source identity in seed-bearing sidecar plus typed generation plan".into());evidence.push(json!({"input_sidecar":sideid,"generation_plan":id}));break;
   }}}
  }
  if resolved.is_none()&&!links.is_empty(){resolved=Some("explicit source path already accounted in pinned prior exposure inventory".into());}
  rows.push(json!({"original_artifact":artifact,"group":group(p),"resolution":resolved,"exposure_keys":links,"evidence":evidence,"schema":schema,"top_level_keys":topkeys,"candidate_manifests":named_manifests}));
 }
 let mut context=Vec::new();for issue in prior["lineage_context_read_issues"].as_array().ok_or("missing context issues")? {let p=issue["path"].as_str().ok_or("missing context path")?;match load(Path::new(p)){Ok((v,id))=>{let mut links=BTreeMap::new();for src in sources(&v){if let Some(keys)=known.get(&src){links.insert(src,keys.clone());}}
  context.push(json!({"original_issue":issue,"artifact":id,"schema":v["schema"],"explicit_observation_id":v["observation_id"],"explicit_known_source_links":links,"read_succeeded":true,"lineage_resolved_from_exact_source_path":!links.is_empty()}));metadata.insert(p.into(),(v,id));},Err(e)=>context.push(json!({"original_issue":issue,"read_succeeded":false,"error":e.to_string()}))}}
 // Resolve deleted scratch aliases only when their declared content digest matches an explicitly known source in hashed metadata.
 let mut digest_links=BTreeMap::<String,Vec<Value>>::new();for(v,id)in metadata.values(){let mut objects=Vec::new();identities(v,&mut objects);for object in objects{let p=object["path"].as_str().unwrap();if let Some(keys)=known.get(p){digest_links.entry(object["sha256"].as_str().unwrap().into()).or_default().push(json!({"metadata_artifact":id,"known_source_identity":object,"prior_exposure_keys":keys}));}}}
 for row in &mut context {if row["lineage_resolved_from_exact_source_path"]==true{continue;}let p=row["original_issue"]["path"].as_str().unwrap();if let Some((v,_))=metadata.get(p){let mut matched=Vec::new();for key in["source","input"]{let h=v[key]["sha256"].as_str().unwrap_or("");if let Some(e)=digest_links.get(h){matched.push(json!({"declared_source_identity":v[key],"matching_known_source_metadata":e}));}}if !matched.is_empty(){row["lineage_resolved_from_declared_content_identity"]=json!(true);row["declared_content_identity_links"]=json!(matched);}}}
 for row in &mut rows {if !row["resolution"].is_null(){continue;}let p=row["original_artifact"]["path"].as_str().unwrap().to_owned();if let Some((v,id))=metadata.get(&p){
   if v["schema"]=="holdout-synthetic-control-result-v1"&&v["control"]["seed"].is_number(){let pp=v["plan_identity"]["path"].as_str().ok_or("missing synthetic plan identity")?;let(plan,pid)=load(Path::new(pp))?;if pid==v["plan_identity"]&&plan["schema"]=="holdout-synthetic-control-run-plan-v1"{let mp=plan["manifest"]["path"].as_str().ok_or("missing synthetic manifest identity")?;let(man,mid)=load(Path::new(mp))?;if mid==plan["manifest"]&&man["schema"]=="holdout-synthetic-controls-v1"&&man["controls"].as_array().is_some_and(|a|a.contains(&v["control"])){row["resolution"]=json!("exact control row matched to hash-bound typed synthetic generation manifest and run plan");row["evidence"].as_array_mut().unwrap().push(json!({"result":id,"plan":pid,"generation_manifest":mid}));}}}
   if row["resolution"].is_null(){for key in["source","input"]{if let Some(e)=digest_links.get(v[key]["sha256"].as_str().unwrap_or("")){row["resolution"]=json!("declared source content digest matches explicitly accounted source metadata; scratch pathname differs");row["evidence"].as_array_mut().unwrap().push(json!({"artifact":id,"source":v[key],"matches":e}));}}}
  }}
 let mut symlinks=Vec::new();let mut other=Vec::new();for issue in prior["filesystem_coverage_issues"].as_array().ok_or("missing filesystem issues")?{let p=Path::new(issue["path"].as_str().ok_or("missing filesystem path")?);if issue["reason"]=="symlink not followed"{let target=fs::read_link(p);let canonical=fs::canonicalize(p);let (c,kind)=match canonical {Ok(c)=>{let m=fs::metadata(&c)?;let k=if m.is_dir(){"directory"}else if m.is_file(){"regular_file"}else{"other"};(Some(c),k)},Err(_)=>(None,"unresolved")};symlinks.push(json!({"path":p,"target":target.ok(),"canonical_target":c,"target_kind":kind,"already_identified_exposure_keys":c.as_ref().and_then(|c|known.get(c.to_str()?))}));}else{other.push(issue.clone());}}
 let mut groups=BTreeMap::<String,Value>::new();for row in &rows{let g=row["group"].as_str().unwrap();let summary=groups.entry(g.into()).or_insert(json!({"artifacts":0,"resolved":0,"unresolved":0,"unresolved_paths":[]}));summary["artifacts"]=json!(summary["artifacts"].as_u64().unwrap()+1);let label=if row["resolution"].is_null(){"unresolved"}else{"resolved"};summary[label]=json!(summary[label].as_u64().unwrap()+1);if label=="unresolved"{summary["unresolved_paths"].as_array_mut().unwrap().push(row["original_artifact"]["path"].clone());}}
 let counts=json!({"original_unlinked":rows.len(),"resolved_unlinked":rows.iter().filter(|r|!r["resolution"].is_null()).count(),"unresolved_unlinked":rows.iter().filter(|r|r["resolution"].is_null()).count(),"context_issues":context.len(),"context_reads_resolved":context.iter().filter(|r|r["read_succeeded"]==true).count(),"context_lineage_resolved":context.iter().filter(|r|r["lineage_resolved_from_exact_source_path"]==true||r["lineage_resolved_from_declared_content_identity"]==true).count(),"symlink_records":symlinks.len(),"other_filesystem_issues":other.len()});
 let out=json!({"schema":"innovation-lineage-grouped-followup-v1","status":"partial","complete_review":false,"prior_review":prior_id,"exposure_inventory":inventory_id,"rows":rows,"groups":groups,"context_issue_review":context,"symlink_target_inventory":symlinks,"other_filesystem_issues":other,"new_metadata_read_issues":issues,"counts":counts,"waveform_bytes_read":0,"decoder_runs":0,"metadata_API_calls":0,"evaluation_release_permitted":false,"fresh_independent_holdout_qualified":false,"limitations":["Resolution means declared metadata/source lineage, not rereading waveform hashes or trusted execution attestation.","Prior exposure-key classification is inherited only through exact source-path joins against the pinned inventory, never newly guessed from directory names.","Synthetic recipes are recognized by typed plan and explicit seed-bearing identity sidecars; no root-name-only waiver.","Symlink targets are inventoried but not blanket waived as package data; unreadable tree and unresolved source paths remain blocking.","Local bounded follow-up, not global historical nonexposure proof."],"auditor_source_sha256":hex::encode(Sha256::digest(include_bytes!("exposure_lineage_group_review.rs")))});
 let dest=root.join("work/innovation-exposure-audit-20260911-v4/lineage-group-review-v2.json");let mut f=fs::File::create_new(&dest)?;serde_json::to_writer_pretty(&mut f,&out)?;f.write_all(b"\n")?;println!("{}",json!({"output":dest,"counts":counts}));Ok(())
}
#[cfg(test)]mod tests{use super::*;#[test]fn arbitrary_directory_does_not_resolve_source(){assert!(sources(&json!({"output":"/work/obs-123/file.wav"})).is_empty());}#[test]fn exact_identity_path_needed(){assert!(!identity_mentions(&json!({"path":"/one.wav","sha256":"a".repeat(64)}),"/two.wav"));}#[test]fn decode_word_alone_does_not_make_weather_contract(){assert!(nonwaveform_contract(&json!({"task":"decode_success_given_signal"})).is_none());}}
