//! Verify existing fixture contents; no signal processing, downloads, or release gate mutation.
use serde_json::{json,Value};use sha2::{Digest,Sha256};use std::{fs,path::Path,io::Write,process::{Command,Stdio}};
type R<T>=Result<T,Box<dyn std::error::Error>>;const ROOT:&str="/home/ubuntu/telemetry-yield";
fn digest(b:&[u8])->String{hex::encode(Sha256::digest(b))}
fn load(p:&Path)->R<(Value,Value)>{let b=fs::read(p)?;Ok((serde_json::from_slice(&b)?,json!({"path":p,"sha256":digest(&b),"bytes":b.len()})))}
fn b64(b:&[u8])->String{let chars=b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";let mut out=String::new();let(mut x,mut bits)=(0u32,0);for byte in b{x=(x<<8)|u32::from(*byte);bits+=8;while bits>=6{bits-=6;out.push(chars[((x>>bits)&63)as usize]as char);}}if bits>0{out.push(chars[((x<<(6-bits))&63)as usize]as char);}out}
fn git(repo:&Path,args:&[&str])->R<String>{let o=Command::new("/usr/bin/git").arg("-C").arg(repo).args(args).output()?;if !o.status.success(){return Err(String::from_utf8_lossy(&o.stderr).into_owned().into());}Ok(String::from_utf8(o.stdout)?.trim().into())}
fn main()->R<()>{let root=Path::new(ROOT);let(input,input_id)=load(&root.join("work/innovation-exposure-audit-20260911-v4/lineage-group-review-v2.json"))?;let repo=root.join("work/golden/satellite-recordings");let head=git(&repo,&["rev-parse","HEAD"])?;
 let mut rows=Vec::new();let mut verified_bytes=0u64;let recipe=root.join("tests/test_scientific_campaign_runner_v1.py");let recipe_bytes=fs::read(&recipe)?;let recipe_id=json!({"path":recipe,"sha256":digest(&recipe_bytes),"bytes":recipe_bytes.len()});let zero_hash=digest(&[0u8;64]);
 for row in input["rows"].as_array().ok_or("missing rows")?.iter().filter(|r|r["resolution"].is_null()){
 let p=Path::new(row["original_artifact"]["path"].as_str().ok_or("missing path")?);let mut resolution=Value::Null;let mut proof=Value::Null;
 if p.starts_with(&repo)&&p.extension().is_some_and(|s|s=="wav"){
  let rel=p.strip_prefix(&repo)?.to_str().ok_or("nonUTF8 filename")?;let tree=git(&repo,&["ls-tree","HEAD","--",rel])?;let fields=tree.split_whitespace().collect::<Vec<_>>();
  if fields.len()==4&&fields[1]=="blob"&&fields[3]==rel{let b=fs::read(p)?;verified_bytes+=b.len()as u64;let mut child=Command::new("/usr/bin/git").arg("-C").arg(&repo).args(["hash-object","--stdin"]).stdin(Stdio::piped()).stdout(Stdio::piped()).spawn()?;child.stdin.take().unwrap().write_all(&b)?;let o=child.wait_with_output()?;let actual=String::from_utf8(o.stdout)?.trim().to_owned();if !o.status.success()||actual!=fields[2]{return Err("current fixture differs from stored Git blob".into());}
   let history=git(&repo,&["log","-1","--format=%H %ct","--",rel])?;let h=history.split_whitespace().collect::<Vec<_>>();let seconds=h.get(1).ok_or("missing commit timestamp")?.parse::<i64>()?;
   proof=json!({"repository_head":head,"git_blob":actual,"last_change_commit":h[0],"commit_unix_seconds":seconds,"actual_file_sha256":digest(&b),"actual_file_bytes":b.len(),"historical_window_start_unix_seconds":1781222400i64});
   if seconds<1781222400{resolution=json!("byte-exact tracked upstream fixture revision predates historical observation window in stored Git history");}
  }
 }else if let Some((site,rel))=p.to_str().unwrap().split_once("/site-packages/"){
  if rel.starts_with("scipy/io/tests/data/")&&p.extension().is_some_and(|x|x=="wav"){
   let sp=Path::new(site).join("site-packages");for e in fs::read_dir(&sp)?{let q=e?.path();let name=q.file_name().unwrap().to_string_lossy();if !name.starts_with("scipy-")||!name.ends_with(".dist-info"){continue;}let rp=q.join("RECORD");if !rp.is_file(){continue;}let bytes=fs::read(&rp)?;let text=std::str::from_utf8(&bytes)?;
    if let Some(line)=text.lines().find(|line|line.split(',').next()==Some(rel)){let parts=line.split(',').collect::<Vec<_>>();if parts.len()!=3||!parts[1].starts_with("sha256="){continue;}let b=fs::read(p)?;verified_bytes+=b.len()as u64;let sha=Sha256::digest(&b);if parts[1][7..]!=b64(&sha)||parts[2].parse::<usize>()?!=b.len(){return Err("wheel fixture content does not match RECORD".into());}resolution=json!("byte-exact scipy distribution test fixture verified against installed wheel RECORD");proof=json!({"record":{"path":rp,"sha256":digest(&bytes),"bytes":bytes.len()},"record_line":line,"actual_file_sha256":hex::encode(sha),"actual_file_bytes":b.len()});break;}
   }
  }
 }else if p.file_name().is_some_and(|s|s=="synthetic.ci16")&&row["original_artifact"]["bytes"]==64{
  let b=fs::read(p)?;verified_bytes+=b.len()as u64;let text=std::str::from_utf8(&recipe_bytes)?;let zero=b==[0u8;64]&&text.contains("source.write_bytes(bytes(64))");let intentional_drift=b.len()==64&&b[..60]==[0u8;60]&&b[60..]==*b"bad!"&&text.contains("source.write_bytes(bytes(60) + b'bad!')");if zero||intentional_drift{resolution=json!("exact64-byte fake-context fixture or explicit bad!-suffix drift mutation matches preserved test generator; not a received satellite waveform");proof=json!({"actual_file_sha256":digest(&b),"actual_file_bytes":b.len(),"generator_source":recipe_id,"intentional_input_drift_test":intentional_drift});}
 }else if p.extension().is_some_and(|s|s=="json") {
  let(v,id)=load(p)?;let receipt=p.parent().and_then(|q|q.parent()).map(|q|q.join("process-receipt.json"));if let Some(rp)=receipt.filter(|q|q.is_file()){let(r,rid)=load(&rp)?;let raw_marker=r["result"]["path"]==p.to_str().unwrap()&&r["result"]["sha256"]==id["sha256"]&&v==json!({"synthetic":true});let normalized=v["unit"]==r["unit"]&&v["status"]==r["status"]&&v["fingerprint"]==r["attempt_fingerprint"]&&v.as_object().is_some_and(|m|m.len()==3);if r["unit"]["source"]["sha256"]==zero_hash&&r["unit"]["source"]["size_bytes"]==64&&(raw_marker||normalized){resolution=json!("fake decoder marker or matching normalization is bound by process receipt to64-zero-byte test input");proof=json!({"result":id,"process_receipt":rid,"generator_source":recipe_id,"raw_synthetic_marker":raw_marker,"exact_mock_normalization":normalized});}}
 }
 rows.push(json!({"path":p,"group":row["group"],"resolution":resolution,"proof":proof}));
 }
 if git(&repo,&["rev-parse","HEAD"])?!=head{return Err("repository HEAD changed during audit".into());}
 let resolved=rows.iter().filter(|r|!r["resolution"].is_null()).count();let pending=rows.iter().filter(|r|r["resolution"].is_null()).count();
 let out=json!({"schema":"innovation-exposure-fixture-content-review-v1","status":"partial","complete_review":false,"parent_review":input_id,"rows":rows,"content_bytes_hashed_without_sample_interpretation":verified_bytes,"additional_resolved_artifacts":resolved,"remaining_artifacts":pending,"all_original_artifacts":876,"total_resolved_in_both_reviews":input["counts"]["resolved_unlinked"].as_u64().unwrap()+resolved as u64,"metadata_API_calls":0,"decoder_runs":0,"downloads":0,"signal_samples_interpreted":0,"evaluation_release_permitted":false,"fresh_independent_holdout_qualified":false,"limitations":["Stored Git commit dates are local repository provenance, not an external timestamp authority.","Wheel RECORD establishes exact distribution fixture content, not an official RF acquisition manifest.","Unmatched fixtures, remaining decoder source chains and filesystem coverage exceptions are not waived.","Hash-only existing-file verification does not inspect signal features or decoder outcomes, and does not expose new candidate audio."],"auditor_source_sha256":digest(include_bytes!("exposure_content_lineage.rs"))});let dest=root.join("work/innovation-exposure-audit-20260911-v4/lineage-content-review-v2.json");let mut f=fs::File::create_new(&dest)?;serde_json::to_writer_pretty(&mut f,&out)?;f.write_all(b"\n")?;println!("{}",json!({"output":dest,"resolved":resolved,"remaining":pending,"bytes_hashed":verified_bytes}));Ok(())}
#[cfg(test)]mod tests{use super::*;#[test]fn base64url_without_padding(){assert_eq!(b64(b"f"),"Zg");assert_eq!(b64(b"fo"),"Zm8");assert_eq!(b64(b"foo"),"Zm9v");assert_eq!(b64(&[255,255,255]),"____");}#[test]fn zero_test_source_digest(){assert_eq!(digest(&[0u8;64]),"f5a5fd42d16a20302798ef6ed309979b43003d2320d9f0e8ea9831a92759fb4b");}}
